name: colasol
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  riverpod_annotation:
  simple_animations: ^5.0.2
  supercharged: ^2.1.1

  cupertino_icons: ^1.0.2
  share_plus: ^7.1.0
  flutter_hooks: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  riverpod_generator:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
